version: '3'

services:
  jira-guru:
    build: .
    ports:
      - "3002:3000"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - ./src/feedback:/app/src/feedback
    environment:
      - NODE_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    command: npm start
